apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: go-stripe-webhook-k8s
spec:
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-stripe-webhook-k8s
