apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: go-stripe-webhook

resources:
    - ../../base
    - route.yaml

images:
    - name: go-stripe-webhook-k8s
      newName: 234290944523.dkr.ecr.eu-west-1.amazonaws.com/go-stripe-webhook-k8s
      newTag: latest
